# Using Decision trees and Random forests to predict Hearts diseases

In [1]:
import pandas as pd
import numpy as np
from pprint import pprint, pformat
import logging
logging.basicConfig(level=logging.DEBUG, format='%(message)s')

We will build a simple logging function to make debugging easier.

In [2]:
global logger
logger = logging.getLogger()
def log(*args, separator=' ', logger=logger):
    '''
    Logs args into the console using logger, separating them by separator.
    A logger must be defined externally.
    '''
    str_args = [str(arg) for arg in args]
    string = separator.join(str_args)
    logger.debug(string)

In [3]:
logger.disabled = False
#Example:
a = np.eye(2)
b = 1
log(a,b)

[[1. 0.]
 [0. 1.]] 1


## Importing and visualizing the data

In [4]:
# pd.read_csv(

## Decision trees

1. Make a tree constructor based on the algorithm from fig. 18.5 of [Norvig] and/or algorithm 8.1 of [Gareth].
2. Allow for both categorical and continuous variables: maybe ask the user to specify what variables are continuous and how many splits to perform on each step. Sklearn does not handle categorical variables super easily, so this can actually be useful. Decide on a stopping criterion, maybe even allow for different ones.
3. Understand why pruning works as [Hastie] says and using [Breiman], and then implement it as [Hastie] describes.
4. Apply to the data. Maybe even apply on only two variables first and plot the regions as [Gareth] does for the Hitters data.

### Regression trees [Gareth]

In [5]:
def binary_split(examples, predictor_to_split_idx, cutpoint):
    '''
    examples is a (# examples, p+1) numpy array where p is the number of predictors. The last column contains the responses.
    Splits the predictor_to_split in two at cutpoint.
    Returns a tuple with two (, p+1) numpy arrays of examples:
        1: examples whose predictor_to_split is < cutpoint.
        2: examples whose predictor_to_split is >= cutpoint.
    '''
    predictors_to_split = examples[:, predictor_to_split_idx] #Column vector with the value for the predictor to split for all the examples.
    mask = predictors_to_split < cutpoint #Boolean mask with True values where predictor to split < cutpoint.
    set1 = examples[mask, :]
    set2 = examples[np.logical_not(mask), :] #Selects the examples where predictor to split >= cutpoint.
    return set1, set2

Small test:

In [6]:
exs = np.array([[1,2,3],[1,5,6]])
j = 1 #index of the split variable
cutpoints = [1, 3, 5]
for s in cutpoints:
    set1, set2 = binary_split(exs, j, s)
    xj_set1 = set1[:, j] #All the xjs in set1. These should all be < s.
    xj_set2 = set2[:, j] #All the xjs in set2. These should all be >= s.
    print('xj values from in set1: {}, cutpoint = {}, xj values from in set1: {}'.format(xj_set1, s, xj_set2))

xj values from in set1: [], cutpoint = 1, xj values from in set1: [2 5]
xj values from in set1: [2], cutpoint = 3, xj values from in set1: [5]
xj values from in set1: [2], cutpoint = 5, xj values from in set1: [5]


In [7]:
exs[0,:-1]

array([1, 2])

It's working!

In [8]:
def optimal_binary_split(examples, predictors_to_split_indices, grid_step_number=10, debug_prints=False):
    '''
    Splits the examples array at the best cutpoint and using the best predictor.
    ------------
    Parameters:
    examples is a (# examples, p+1) numpy array where p is the number of predictors. The last column contains the responses.
    predictors_to_split_indices is a list containing the indices of the predictors we want to split. It can also be the string 'all', in which case we split all the predictors.
    #cutpoints is a (len(predictors_to_split_indices, ) array ... It can also be the string ...
    '''
    ###Set up logger
    global logger
    if debug_prints:
        logger.disabled = False
    else:
        logger.disabled = True #Must write this explicitly to not have problems when running inside other functions.
    ###
    p = len(examples[0, :-1]) #Number of predictors.
    smallest_cost = 100000
    best_split = (0, 0, smallest_cost) #placeholder for best_split.
    for j in predictors_to_split_indices:
        #Construct array of cutpoints:
        max_cutpoint =  max(examples[:, j]) 
        step = (max_cutpoint - min(examples[:,j]))/grid_step_number #grid step
        min_cutpoint =  min(examples[:, j]) + step  #We do not want to include min(examples[:,j]) itself, since that would lead to cases with no points 'on the left' because of how binary_split() was defined.
        if min_cutpoint == max_cutpoint: #Examples have the same jth predictor value, so no split can be made, so we abort the split.
            log('Skip j = {}'.format(j))
            continue #Goes to the top of this loop again.
        cutpoints = np.linspace(min_cutpoint, max_cutpoint, grid_step_number) 
        log('Cutpoints for j={}: {}, step: {}'.format(j, cutpoints, step))
        for s in cutpoints:
            set1, set2 = binary_split(examples, j, s)
            log('s,j: {}, {} \n set1 --- set2: {} --- {}'.format(s,j, set1, set2))
            y_1 = set1[:, p]; y_2 = set2[:, p] #Extract the responses.
            y1_estimate = np.average(y_1); y2_estimate = np.average(y_2) #Estimates will simply be the averages.
            cost = np.sum(np.square(y_1 - y1_estimate)) + np.sum(np.square(y_2 - y2_estimate))
            if cost < smallest_cost:
                log('NEW COST: {}'.format(cost))
                smallest_cost = cost
                best_split = (j, s, smallest_cost) #Store info about this iteration.
    return best_split

In [9]:
#Example.
exs = np.array([[1,4,7],[1,5,2],[1,2,8]])
print('Examples: \n {}'.format(exs))
p = len(exs[0, :-1]) #Number of predictors.
predictors_to_split_indices = range(p) #List with indices of predictors to split.
optimal_binary_split(exs, predictors_to_split_indices, debug_prints=True)

Skip j = 0
Cutpoints for j=1: [2.3 2.6 2.9 3.2 3.5 3.8 4.1 4.4 4.7 5. ], step: 0.3
s,j: 2.3, 1 
 set1 --- set2: [[1 2 8]] --- [[1 4 7]
 [1 5 2]]
NEW COST: 12.5
s,j: 2.5999999999999996, 1 
 set1 --- set2: [[1 2 8]] --- [[1 4 7]
 [1 5 2]]
s,j: 2.9, 1 
 set1 --- set2: [[1 2 8]] --- [[1 4 7]
 [1 5 2]]
s,j: 3.2, 1 
 set1 --- set2: [[1 2 8]] --- [[1 4 7]
 [1 5 2]]
s,j: 3.5, 1 
 set1 --- set2: [[1 2 8]] --- [[1 4 7]
 [1 5 2]]
s,j: 3.8, 1 
 set1 --- set2: [[1 2 8]] --- [[1 4 7]
 [1 5 2]]
s,j: 4.1, 1 
 set1 --- set2: [[1 4 7]
 [1 2 8]] --- [[1 5 2]]
NEW COST: 0.5
s,j: 4.4, 1 
 set1 --- set2: [[1 4 7]
 [1 2 8]] --- [[1 5 2]]
s,j: 4.7, 1 
 set1 --- set2: [[1 4 7]
 [1 2 8]] --- [[1 5 2]]
s,j: 5.0, 1 
 set1 --- set2: [[1 4 7]
 [1 2 8]] --- [[1 5 2]]


Examples: 
 [[1 4 7]
 [1 5 2]
 [1 2 8]]


(1, 4.1, 0.5)

Notice that the function behaves as expected, clumping together the first and third rows, which indeed have the closest response values 7 and 8.

In [10]:
def recursive_binary_split(examples, max_leaf_population, predictors_to_split_indices='all', grid_step_number=10, debug_prints=False, deep_debug_prints = False):
    '''
    Recursively splits the examples array, building a decision tree with binary splits and stopping when every leaf contains less than max_leaf_population examples.
    ------------
    Parameters:
    examples is a (# examples, p+1) numpy array where p is the number of predictors. The last column contains the responses.
    predictors_to_split_indices is a list containing the indices of the predictors we want to split. It can also be the string 'all', in which case we split all the predictors.
    #cutpoints is a (len(predictors_to_split_indices, ) array ... It can also be the string ...
    '''
    ###Set up logger
    global logger
    if debug_prints:
        logger.disabled = False
    else:
        logger.disabled = True #Must write this explicitly to not have problems when running inside other functions.
    logger_bool = logger.disabled
    ###
    p = len(examples[0, :-1]) #Number of predictors.
    if predictors_to_split_indices == 'all':
        predictors_to_split_indices = range(p) #List with indices of predictors to split.
    regions = [examples] #Initialize list of all regions. Notice that these regions also include the responses.
    tree_log = [regions]
    top_leaf_population = len(examples[:,0])
    while top_leaf_population >= max_leaf_population:
        #Select best region to make split, and split parameters.
        splits_info = [((idx, region), optimal_binary_split(region, predictors_to_split_indices, grid_step_number=grid_step_number, debug_prints=deep_debug_prints)) for (idx,region) in enumerate(regions) if region.shape[0]>0] #The if statement ensures there's at least one example. Want to allow for this eentually!
        logger.disabled = logger_bool #Restore logger.disable (may have been changed by optimal_binary_split()).
        #Find best split.
        costs = [info[1][2] for info in splits_info] #info[1] is tuple (j,s,smallest_cost)
        min_idx = np.argmin(costs)
        best_split = splits_info[min_idx] #Tuple ((idx, region), (j,s,cost))
        #We now make the actual split.
        idx_region, region = best_split[0]
        j = best_split[1][0]
        s = best_split[1][1]
        R1, R2 = binary_split(region, j, s)
        #Substitute region by R1, R2.
        del regions[idx_region]
        regions.extend([R1, R2])
        #Update log and leaf pop:
        tree_log.append(regions)
        top_leaf_population = max([len(region[:,0]) for region in regions])
        log('Current max leaf population: {}'.format(top_leaf_population))
    return regions, tree_log
    

In [11]:
#Example.
exs = np.array([[1,4,7],[1,5,2],[1,2,8]])
print('Examples: \n {}'.format(exs))
recursive_binary_split(exs, 2, debug_prints=True)[0]

Current max leaf population: 2
Current max leaf population: 1


Examples: 
 [[1 4 7]
 [1 5 2]
 [1 2 8]]


[array([[1, 5, 2]]), array([[1, 2, 8]]), array([[1, 4, 7]])]

#### Tree prunning

### Visualizing a decision tree

In [34]:
# Use the Networkx module maybe...
